    --2 < 1 ::Bool
    --4.2 + 2.0 ::Double
    --4.2 + 2 ::Double
    --4 + 2 :: Int
    --(4::Int) + 2 :: Int
    --floor 2.3 ::Int
    --fromIntegral 3 :: Double
    --succ 2.2 ::Double
    --succ 2 ::Int
    --succ (2::Int) ::Int
    --succ 'b' ::Char
    --show 2 ::String
    --show 2.4 ::String

